my_name = str("emobilis")
my_number = int(352)
my_number2 = float(85.984389)
my_bool = bool(True)
my_bool2 = bool(False)
my_comp = complex(1j)
print(my_name)
print(my_number)
print(my_number2)
print(my_bool)
print(my_bool2)
print(my_comp)
